In [1]:
import numpy as np
from sklearn import datasets, preprocessing
from sklearn.model_selection import train_test_split
from neupy import algorithms

In [2]:
dataset = datasets.load_diabetes()

In [3]:
dataset.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [4]:
dataset.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
x_train, x_test, y_train, y_test = train_test_split(
    preprocessing.minmax_scale(dataset.data),
    preprocessing.minmax_scale(dataset.target.reshape(-1, 1)),
    test_size=0.3,random_state=42
)

In [6]:
y_train

array([[0.57009346],
       [0.73520249],
       [0.47975078],
       [0.7258567 ],
       [0.73831776],
       [0.08099688],
       [0.66043614],
       [0.14330218],
       [0.35514019],
       [0.75700935],
       [0.13707165],
       [0.90965732],
       [0.69781931],
       [0.40186916],
       [0.52024922],
       [0.2834891 ],
       [0.17445483],
       [0.30218069],
       [0.72897196],
       [0.51713396],
       [0.8317757 ],
       [0.09345794],
       [0.25545171],
       [0.57632399],
       [0.20560748],
       [0.71028037],
       [0.18691589],
       [0.70716511],
       [0.105919  ],
       [0.16510903],
       [0.54517134],
       [0.16510903],
       [0.68535826],
       [0.46728972],
       [0.0529595 ],
       [0.31775701],
       [0.08722741],
       [0.21495327],
       [0.24610592],
       [0.54205607],
       [0.74766355],
       [0.79750779],
       [0.69470405],
       [0.72274143],
       [0.59190031],
       [0.86604361],
       [0.4517134 ],
       [0.105

In [12]:
grnn = algorithms.GRNN(std=0.3, verbose=False)
grnn.train(x_train, y_train)

In [13]:
y_predicted = grnn.predict(x_test)

In [14]:
y_predicted

array([[0.39351326],
       [0.41168133],
       [0.42156397],
       [0.62151477],
       [0.37153755],
       [0.31629387],
       [0.66765287],
       [0.48554207],
       [0.2112058 ],
       [0.25335398],
       [0.28963763],
       [0.34451357],
       [0.2712495 ],
       [0.51298695],
       [0.24577244],
       [0.25856108],
       [0.5859729 ],
       [0.64677443],
       [0.4680302 ],
       [0.55120366],
       [0.43578584],
       [0.26738858],
       [0.24564198],
       [0.48512865],
       [0.36750298],
       [0.39774434],
       [0.46278112],
       [0.40715621],
       [0.22391718],
       [0.33019714],
       [0.42185496],
       [0.3509374 ],
       [0.30315037],
       [0.44033367],
       [0.42284654],
       [0.49857323],
       [0.29963735],
       [0.35149433],
       [0.44055141],
       [0.22483143],
       [0.25626868],
       [0.27850769],
       [0.37140062],
       [0.42546191],
       [0.4403098 ],
       [0.23957557],
       [0.27732969],
       [0.273

In [15]:
mse = np.mean((y_predicted - y_test) ** 2)
mse

0.029683583826659136